# Site setings
name: "Thorsten's thoughts"
description: "Experiences from real-world projects. Focussing Microsoft Azure, Kubernetes and Infrastructure as Code."
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl:
url: https://thorsten-hans.com
mailchimp_url:  "https://gmail.us20.list-manage.com/subscribe/post?u=5581ba765692a75a48258504e&amp;id=78ce80aba5"
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: UA-117431284-1

image_folder: /assets/images/posts/feature_images
thumbs_folder: /assets/images/posts/feature_thumbs
include:
  - _redirects
  - robots.txt
# RSS Feed settings

feed:
  path: feed.xml
# Author
author:
  name: Thorsten Hans
  email: thorsten.hans@gmail.com
  image: thorsten-hans.jpg
  greetings: Hi there,
  description: I am Thorsten from Germany. I build software for the cloud.
  description2: I do some Kubernetes, Terraform, and Azure. Coding is my passion.
  bio: Thorsten is a developer, consultant, photographer and speaker from the beautiful south-west area in Germany. He loves his zsh-shell, Electron, containers, and Microsoft Azure.

social:
  twitter: ThorstenHans
  github: ThorstenHans
  instagram: ThorstenHans
  linkedin: thorstenhans

twitter:
  card: summary
  site: ThorstenHans
  username: ThorstenHans

# Navigation
navigation:
  - text: Talks & Publications
    url: /talks-and-publications/
  - text: About
    url: /about/
  - text: Subscribe via email
    url: /subscribe-via-email/
  - text: Legal Details
    url: /legal-details/
  - text: Privacy Policy
    url: /privacy-policy/

# Required Plugins
plugins_dir:
  - jekyll-target-blank
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed

# Pagination
paginate: 10
paginate_path: /page-:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
