# Site setings
name: "Thorsten's thoughts"
description: "Experiences from real-world projects. Focussing Microsoft Azure, Kubernetes and Infrastructure as Code."
meta_description: "Thorsten Hans shares his experiences from real-world projects. Focussing Microsoft Azure, Kubernetes and Infrastructure as Code."
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
? baseurl
production_url: https://horace.netlify.com/
disqus: "justgoodthemes"
mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"
cover_image: bc_1.jpg
# Add your GA Tracking Id
? ga_analytics

# Author
author:
  name: "Thorsten Hans"
  image: "thorsten-hans.jpg"
  greetings: "Hi there!"
  description: "My name is Thorsten. I'm a passionate Consultant from the beautiful south-west area in Germany. I love my zsh-shell, Apple, containers, and Microsoft Azure."
  bio: "Daniel is a designer, photographer, speaker, author of a couple of books about typography and the founder of photo magazine Curious."

# Contact form setings
email: thorsten.hans@gmail.com
contact_page_description: "Are you a developer and looking for assistance? Do you have feedback on any of my articles? Or do you have a general question for me?\nDon't be afraid.\nEither use the contact form or tweet at me."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: "ThorstenHans"
github: "ThorstenHans"
medium: "@ThorstenHans"
instagram: "ThorstenHans"
linkedin: "thorstenhans"

# Navigation
navigation:
  - text: Blog
    url: /
  - text: Talks & Publications
    url: /talks-and-publications/
  - text: About
    url: /about/
  - text: Contact Me
    url: /contact/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 10
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
