title: Thorsten Hans
seo_title: Thorsten Hans | Microsoft Azure, Kubernetes & Cloud Native
subtitle: Stories about Microsoft Azure, Kubernetes and Cloud Native Computing
seo_description: Hey, I am Thorsten, a passionate developer and Microsoft MVP focusing on Azure, Kubernetes, and Cloud Native Computing. I share stories and experiences from real-world projects