name: Netlify Trigger (every 3rd hour)
on:
  schedule:
  - cron: "0 */3 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Netlify Hook
      run: curl -X POST ${{ secrets.netlify_build_url }}?trigger_title=GitHub+Hourly+Action
